apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: backend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Gateway → Backend
    - from:
        - namespaceSelector:
            matchLabels:
              name: gate
      ports:
        - protocol: TCP
          port: 3001
        - protocol: TCP
          port: 3002
        - protocol: TCP
          port: 3003
        - protocol: TCP
          port: 3005
        - protocol: TCP
          port: 3010

    # Backend → Backend (internal communication)
    - from:
        - namespaceSelector:
            matchLabels:
              name: backend

  egress:
    # Backend → Data
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 5672

    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
