apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: reporting-service-vpa
  namespace: banking-app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reporting-service
  updatePolicy:
    updateMode: "Off"
