apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loan-route
  namespace: backend
spec:
  parentRefs:
  - name: banking-gateway
    namespace: gate
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/loan
    backendRefs:
    - name: loan-service
      port: 3005
